scenario:
  environment: scenarios.mumt_target_practice

agent:
  namespaces: "/F16_UAV2"            # 공격기 (에디터에서 Team=FriendlyUAV)
  behavior_tree_xml: "hunter_bt.xml"

bt_runner:
  bt_tick_rate: 10.0
  bt_visualiser:
    enabled: True
    screen_width: 600
    screen_height: 600
  profiling_mode: False
