scenario:
  environment: scenarios.mumt_waypoint

agent:
  namespaces: "/F16_UAV1"            # StickController로 웨이포인트 박스 순환
  behavior_tree_xml: "uav1_bt.xml"

bt_runner:
  bt_tick_rate: 10.0
  bt_visualiser:
    enabled: True
    screen_width: 600
    screen_height: 600
  profiling_mode: False
